[tool.cibuildwheel]
before-build = "pip install cython>=3.0 setuptools>=80 wheel"
build = "cp313-* cp314-*"
skip = "pp* *musllinux*"
build-verbosity = 1

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

[tool.cibuildwheel.windows]
archs = ["AMD64"]
